zero_string='44-44'
print "%s = %i" % (zero_string, eval(zero_string))
one_string="44/44"
print "%s = %i" % (one_string, eval(one_string)) 
two_string='((4/4)+(4/4))'
print "%s = %i" % (two_string, eval(two_string))
three_string='((4+4+4)/4)'
print "%s = %i" % (three_string, eval(three_string)) 
#four_string=''
#print "%s = %i" % (four_string, eval(four_string))
five_string = '((4*4+4)/4)'
print "%s = %i" % (five_string, eval(five_string))