print "Welcome to the survey!"
name=raw_input("What is your name? ")
color=raw_input("wWhat is your favorite color? ")
hobby=raw_input("What is your favorite hobby? ")
movie=raw_input("what is your favorite movie? ")
food=raw_input("What is your favorite kind of food? ")
music=raw_input("What is your favorite kind of music? ")
print "%s's favorite color is %s." % (name, color)
print "%s's favorite hobby is %s." % (name, hobby)
print "%s's favorite movie is %s." % (name, movie)
print "%s's favorite food is %s." % (name, food)
print "%s's favorite music is %s." % (name, music)